/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.itz.proyectofinal.vistas;

import edu.itz.proyectofinal.control.Control;
//import edu.itz.proyectofinal.sintaxis.AnaSintaxis;
import javax.swing.JLabel;
import javax.swing.JTextArea;
/**
 *
 * @author flofl
 */
public class Ventana extends javax.swing.JFrame {
    Control c;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        c= new Control(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsCodigo = new javax.swing.JScrollPane();
        txtCodigo = new javax.swing.JTextArea();
        jsMensajes = new javax.swing.JScrollPane();
        txtMensajes = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblArchivo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmnuArchivo = new javax.swing.JMenu();
        mnuAbrir = new javax.swing.JMenuItem();
        mnuLimpiar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        jmnuCompilar = new javax.swing.JMenu();
        mnuLexico = new javax.swing.JMenuItem();
        jmTablas = new javax.swing.JMenu();
        mnuTablaTokens = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtCodigo.setColumns(20);
        txtCodigo.setRows(5);
        jsCodigo.setViewportView(txtCodigo);

        txtMensajes.setEditable(false);
        txtMensajes.setColumns(20);
        txtMensajes.setRows(5);
        jsMensajes.setViewportView(txtMensajes);

        jLabel1.setText("Archivo:");

        jmnuArchivo.setText("Archivo");

        mnuAbrir.setText("Abrir");
        mnuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirActionPerformed(evt);
            }
        });
        jmnuArchivo.add(mnuAbrir);

        mnuLimpiar.setText("Limpiar");
        mnuLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLimpiarActionPerformed(evt);
            }
        });
        jmnuArchivo.add(mnuLimpiar);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jmnuArchivo.add(mnuSalir);

        jMenuBar1.add(jmnuArchivo);

        jmnuCompilar.setText("Compilar");

        mnuLexico.setText("Léxico");
        mnuLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLexicoActionPerformed(evt);
            }
        });
        jmnuCompilar.add(mnuLexico);

        jMenuBar1.add(jmnuCompilar);

        jmTablas.setText("Tablas");

        mnuTablaTokens.setText("Tabla Tokens");
        mnuTablaTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTablaTokensActionPerformed(evt);
            }
        });
        jmTablas.add(mnuTablaTokens);

        jMenuBar1.add(jmTablas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addComponent(jsCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jsMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirActionPerformed
        c.abrirArchivo();
    }//GEN-LAST:event_mnuAbrirActionPerformed

    private void mnuLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLimpiarActionPerformed
        c.limpiar();
    }//GEN-LAST:event_mnuLimpiarActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLexicoActionPerformed
        c.analizarTexto();
    }//GEN-LAST:event_mnuLexicoActionPerformed

    private void mnuTablaTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTablaTokensActionPerformed
         c.mostrarTablaTokens();
         
    }//GEN-LAST:event_mnuTablaTokensActionPerformed

     public JTextArea getTxtContenido() {
        return txtCodigo;
    }

    public JLabel getLblArchivo() {
        return lblArchivo;
    }

    public JTextArea getTxtSalida() {
        return txtMensajes;
    }
    public JTextArea getTablaLexemas() {
        return txtCodigo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmTablas;
    private javax.swing.JMenu jmnuArchivo;
    private javax.swing.JMenu jmnuCompilar;
    private javax.swing.JScrollPane jsCodigo;
    private javax.swing.JScrollPane jsMensajes;
    private javax.swing.JLabel lblArchivo;
    private javax.swing.JMenuItem mnuAbrir;
    private javax.swing.JMenuItem mnuLexico;
    private javax.swing.JMenuItem mnuLimpiar;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenuItem mnuTablaTokens;
    private javax.swing.JTextArea txtCodigo;
    private javax.swing.JTextArea txtMensajes;
    // End of variables declaration//GEN-END:variables
}
